### ISSUE TITLE
about speaker-face step

### ISSUE THREAD

**Issue by JINzezhong7** [TaoRuijie/AVCleanse#1]
Thanks for you open source code. In paper, I guess you train speaker and face embedding network respectively. Then, use it to clean the data. But in speaker-face folder, you train speaker and face embedding network together. I want to ask why you do this. Thank you.

**Comment by TaoRuijie** [comment]
I just put them into the same code for training and evaluation, but two models are independent. The motivation is to check the multi-model speaker recognition results.
